### ISSUE TITLE
Little question about Robocon...

### ISSUE THREAD

**Issue by zardchim** [spiralray/nhk2015_back_ros#1]
Hello! This is chimlee from Hong Kong.

I wonder why most autonomous robot failed in the competition? They looks awesome, for example, yours and KIT (Kitakyushu Institute of Technology) looks awesome!

( Sorry for raising issue for these question >.< But I can't find your contact)

**Comment by spiralray** [comment]
Thank you for asking a question.

You may mistakenly understand KIT.
KIT is not Kitakyushu Institute of Technology but Kanazawa Institute of Technology.
Moreover, robots of KIT are not automatic. Those robots contains KinectV2, but it's optional.

Other automatic robots participated in the competition.
NIT(Nagoya Institute of Technology), Tokyo University, Kyushu University, etc...

In my opinion, robots of NIT are perfect.
However, in the competition, bluetooth interference occurred, then their robots didn't work well.

It was a pleasure to hear that China teams will participate in ABU Robocon 2015.
I'm looking forward to seeing Chinese excellent automatic robots!

If you have any question, ask me anything on the Twitter (@spiralray)

**Comment by zardchim** [comment]
Thank you for your answering!

just to make clarify that Hong Kong is not part of the China Team  Hong Kong & China are separated as " One country two systems",  and we have our own team :) 

I have followed your twitter :)  But it seems i cant message you and my Japanese it bad XD
